name: OpenJDK build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 18
      - run: mvn clean compile assembly:single
      - run: java -jar target/api-1.0.jar
